#!/usr/bin/env ruby

require 'fileutils'
require 'tmpdir'

def pipe(command)
  puts command
  output = ""
  IO.popen(command) do |io|
    until io.eof?
      buffer = io.gets
      output << buffer
      puts buffer
    end
  end

  output
end

workspace_dir, output_dir = ARGV
bundler    = "bundler-1.4.0.pre.2"
ruby       = "ruby-2.0.0"
vendor_url = "https://s3-external-1.amazonaws.com/heroku-buildpack-ruby"

FileUtils.mkdir_p(ruby)
Dir.chdir(ruby) do
  pipe "curl #{vendor_url}/#{ruby}.tgz -s -o - | tar xzf -"
end
FileUtils.mkdir_p(bundler)
Dir.chdir(bundler) do
  pipe "curl #{vendor_url}/#{bundler}.tgz -s -o - | tar xzf -"
end

ext = "ext"

FileUtils.mkdir_p(ext)
Dir.chdir(ext) do
  pipe "curl #{vendor_url}/libyaml-0.1.4.tgz -s -o - | tar xzf -"
end

File.open('Gemfile', 'w') do |file|
  file.puts <<-GEMFILE
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use postgresql as the database for Active Record
gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem "rails_12factor"

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
gem 'unicorn'

gem "puma"

gem "nokogiri"

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
  GEMFILE
end

File.open('Gemfile.lock', 'w') do |file|
  file.puts <<-GEMFILE_LOCK
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.0.0)
      actionpack (= 4.0.0)
      mail (~> 2.5.3)
    actionpack (4.0.0)
      activesupport (= 4.0.0)
      builder (~> 3.1.0)
      erubis (~> 2.7.0)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    activemodel (4.0.0)
      activesupport (= 4.0.0)
      builder (~> 3.1.0)
    activerecord (4.0.0)
      activemodel (= 4.0.0)
      activerecord-deprecated_finders (~> 1.0.2)
      activesupport (= 4.0.0)
      arel (~> 4.0.0)
    activerecord-deprecated_finders (1.0.3)
    activesupport (4.0.0)
      i18n (~> 0.6, >= 0.6.4)
      minitest (~> 4.2)
      multi_json (~> 1.3)
      thread_safe (~> 0.1)
      tzinfo (~> 0.3.37)
    arel (4.0.0)
    atomic (1.1.14)
    bcrypt-ruby (3.0.1)
    builder (3.1.4)
    coffee-rails (4.0.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0.beta, < 5.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.6.3)
    erubis (2.7.0)
    execjs (2.0.1)
    hike (1.2.3)
    i18n (0.6.5)
    jbuilder (1.5.1)
      activesupport (>= 3.0.0)
      multi_json (>= 1.2.0)
    jquery-rails (3.0.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.8.0)
    kgio (2.8.1)
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.25)
    mini_portile (0.5.1)
    minitest (4.7.5)
    multi_json (1.8.0)
    nokogiri (1.6.0)
      mini_portile (~> 0.5.0)
    pg (0.16.0)
    polyglot (0.3.3)
    puma (2.6.0)
      rack (>= 1.1, < 2.0)
    rack (1.5.2)
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (4.0.0)
      actionmailer (= 4.0.0)
      actionpack (= 4.0.0)
      activerecord (= 4.0.0)
      activesupport (= 4.0.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.0.0)
      sprockets-rails (~> 2.0.0)
    rails_12factor (0.0.2)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.1)
    rails_stdout_logging (0.0.2)
    railties (4.0.0)
      actionpack (= 4.0.0)
      activesupport (= 4.0.0)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.12.0)
    rake (10.1.0)
    rdoc (3.12.2)
      json (~> 1.4)
    sass (3.2.10)
    sass-rails (4.0.0)
      railties (>= 4.0.0.beta, < 5.0)
      sass (>= 3.1.10)
      sprockets-rails (~> 2.0.0)
    sdoc (0.3.20)
      json (>= 1.1.3)
      rdoc (~> 3.10)
    sprockets (2.10.0)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.0.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (~> 2.8)
    thor (0.18.1)
    thread_safe (0.1.3)
      atomic
    tilt (1.4.1)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    turbolinks (1.3.0)
      coffee-rails
    tzinfo (0.3.37)
    uglifier (2.2.1)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)
    unicorn (4.6.3)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)

PLATFORMS
  ruby

DEPENDENCIES
  bcrypt-ruby (~> 3.0.0)
  coffee-rails (~> 4.0.0)
  jbuilder (~> 1.2)
  jquery-rails
  nokogiri
  pg
  puma
  rails (= 4.0.0)
  rails_12factor
  sass-rails (~> 4.0.0)
  sdoc
  turbolinks
  uglifier (>= 1.3.0)
  unicorn
  GEMFILE_LOCK
end

gem_home     = "#{output_dir}/vendor/bundle/ruby/2.0.0"
gem_path     = "#{gem_home}:#{workspace_dir}/#{bundler}"
path         = "#{workspace_dir}/#{ruby}/bin:#{workspace_dir}/#{bundler}/bin:$PATH"
yaml_include = "#{workspace_dir}/#{ext}/include"
yaml_lib     = "#{workspace_dir}/#{ext}/lib"

env  = {
  "BUNDLE_GEMFILE"                => "#{workspace_dir}/Gemfile",
  "BUNDLE_CONFIG"                 => "#{`pwd`.chomp}/.bundle/config",
  "PATH"                          => path,
  "GEM_HOME"                      => gem_home,
  "GEM_PATH"                      => gem_path,
  "CPATH"                         => "#{yaml_include}:$CPATH",
  "CPPATH"                        => "#{yaml_include}:$CPPATH",
  "LIBRARY_PATH"                  => "#{yaml_lib}:$LIBRARY_PATH",
  "NOKOGIRI_USE_SYSTEM_LIBRARIES" => "true"
}.to_a.map {|k,v| "#{k}=#{v}" }.join(" ")
cmd  = "bundle install"
opts = "--path #{output_dir}/vendor/bundle --deployment -j4"
pipe("env #{env} #{cmd} #{opts}")
